FROM node:alpine

ARG CPUS=6

ARG MEMORY=6g
# Install dependencies
RUN apt-get update && \
    apt-get install -y build-essential python libavcodec-dev libavformat-dev libavdevice-dev libssl-dev sudo

WORKDIR /app

COPY ./package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV=dev

EXPOSE 3001

CMD  ["yarn","start:dev"]